spring.datasource.url=jdbc:postgresql://localhost:5432/equora
spring.datasource.username=postgres
spring.datasource.password=Ayushi@2317
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=Thisismysecrxcetkeyno-oneknownsthisisthekey

spring.servlet.session.cookie.same-site=strict